"""
Django settings for our project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""


# Built-in
import os
import sys

# --------------------------------------------------------------------------------
# > Directories
# --------------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")


# --------------------------------------------------------------------------------
# > Applications
# --------------------------------------------------------------------------------
# Directories that will be searched for apps
# sys.path.insert(0, os.path.join(BASE_DIR, "api"))

INSTALLED_APPS = [
    # --------------------
    # Django
    # --------------------
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.sitemaps",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    # --------------------
    # Third-party
    # --------------------
    "jklib",
    "rest_framework",
    # --------------------
    # API
    # --------------------
    "api.core",
    "api.contact",
    "api.users",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAdminUser",  # Root and default access
    ],
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # 'django.middleware.locale.LocaleMiddleware',  # Required for translations to work
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "server_config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(
                BASE_DIR, "templates"
            ),  # The root /template is also searched for templates
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server_config.wsgi.application"


# --------------------------------------------------------------------------------
# > Password and logins
# --------------------------------------------------------------------------------
LOGIN_URL = "user_login"
LOGIN_REDIRECT_URL = "user_account"

# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 10,},
    },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# --------------------------------------------------------------------------------
# > Internationalization
# --------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = (("fr-fr", "Français"),)


# --------------------------------------------------------------------------------
# > Email settings
# --------------------------------------------------------------------------------
EMAIL_CSS = "core/css/emails.css"
# Contact
CONTACT_EMAIL_TEMPLATES = {
    "alert": "common/emails/contact_alert.html",
    "confirm": "common/emails/contact_confirm.html",
}


# --------------------------------------------------------------------------------
# > Others
# --------------------------------------------------------------------------------
FIRST_DAY_OF_WEEK = 1
SITE_ID = 1


# --------------------------------------------------------------------------------
# > Local Settings
# --------------------------------------------------------------------------------
# It should AT LEAST contain the following:
#   Security:
#       SECRET_KEY
#       DEBUG
#       ALLOWED_HOST
#       SECURE_SSL_REDIRECT
#       FRONTEND_ROOT_URL
#   reCAPTCHA
#       RECAPTCHA_SITE_KEY
#       RECAPTCHA_SECRET_KEY
#   Cookies
#       CSRF_COOKIE_HTTPONLY
#       CSRF_COOKIE_SECURE
#   Session
#       SESSION_COOKIE_AGE
#       SESSION_COOKIE_HTTPONLY
#       SESSION_COOKIE_SECURE
#       SESSION_ENGINE
#       SESSION_EXPIRE_AT_BROWSER_CLOSE
#   Databases:
#       DATABASES
#   Emails:
#       EMAIL_BACKEND
#       EMAIL_HOST
#       EMAIL_PORT
#       EMAIL_USE_TLS
#       EMAIL_HOST_USER
#       EMAIL_HOST_PASSWORD
try:
    from .local_settings import *
except ImportError as e:
    print(e)
    sys.exit(0)
