# Generated by Django 3.0.9 on 2020-08-05 22:26

# Django
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Nom",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Société",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "subject",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Objet",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        max_length=2000,
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="Message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contacts",
                "ordering": ["-id"],
            },
        ),
    ]
