# Generated by Django 3.1.1 on 2020-10-18 16:40

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IpAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("ip", models.GenericIPAddressField(protocol="IPv4", unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "None"), (2, "Whitelisted"), (3, "Blacklisted")],
                        default=1,
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(
                        db_index=True,
                        default=None,
                        help_text="Expires at the end of said date",
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("comment", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "IP Address",
                "verbose_name_plural": "IP Addresses",
                "db_table": "core_ip_addresses",
                "ordering": ["-id"],
            },
        ),
    ]
