# Generated by Django 3.1.5 on 2021-02-01 18:51

# Django
from django.db import migrations, models

# Personal
import jklib.django.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthcheckDummy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Healthcheck Dummy",
                "verbose_name_plural": "Healthcheck Dummies",
                "db_table": "core_healthcheck_dummies",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="NetworkRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("ip", models.GenericIPAddressField(protocol="IPv4", unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "None"), (2, "Whitelisted"), (3, "Blacklisted")],
                        default=1,
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Expires at the end of said date",
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "comment",
                    jklib.django.db.fields.TrimCharField(blank=True, max_length=255),
                ),
            ],
            options={
                "verbose_name": "Network Rule",
                "verbose_name_plural": "Network Rules",
                "db_table": "core_network_rules",
                "ordering": ["-id"],
            },
        ),
    ]
