# Generated by Django 3.0.9 on 2020-08-07 21:40

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api.users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token", old_name="hash_value", new_name="value",
        ),
    ]
