# Generated by Django 3.0.9 on 2020-08-08 10:21

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api.users", "0002_auto_20200807_2340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Verified"
            ),
        ),
    ]
