# Generated by Django 3.1.5 on 2021-04-06 22:43

# Django
from django.db import migrations, models

# Personal
import jklib.django.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        protocol="IPv4", unique=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "None"), (1, "Whitelisted"), (2, "Blacklisted")],
                        db_index=True,
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Expires at the end of said date",
                        null=True,
                        verbose_name="Expires on",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "comment",
                    jklib.django.db.fields.TrimCharField(
                        blank=True, max_length=255, verbose_name="Comment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Rule",
                "verbose_name_plural": "Network Rules",
                "db_table": "security_network_rules",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SecurityToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                (
                    "value",
                    models.CharField(
                        max_length=1000, unique=True, verbose_name="Token value"
                    ),
                ),
                ("expired_at", models.DateTimeField(verbose_name="Expires at")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used at"),
                ),
                (
                    "is_active_token",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
                "db_table": "security_tokens",
                "ordering": ["-id"],
            },
        ),
    ]
