# Generated by Django 3.1.5 on 2021-04-05 17:05

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitytoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
