# Generated by Django 3.1.5 on 2021-04-06 22:43

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="securitytoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="networkrule",
            index=models.Index(
                fields=["active", "expires_on", "status"],
                name="security_ne_active_52079e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitytoken",
            index=models.Index(
                fields=["user", "type", "is_active_token"],
                name="security_to_user_id_5af2c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitytoken",
            index=models.Index(
                fields=["type", "value"], name="security_to_type_996452_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitytoken",
            index=models.Index(
                fields=["used_at", "expired_at"], name="security_to_used_at_13a71e_idx"
            ),
        ),
    ]
